CREATE TABLE EMPLOYEES
(
EMP_ID INT PRIMARY KEY,
EMP_NAME CHAR(255),
HIRE_DATE DATE,
SALARY MONEY,
CITY VARCHAR(255)
)

CREATE TABLE DEPARTMENTS
(
DEPT_ID INT PRIMARY KEY NOT NULL,
DEPT_NAME CHAR(100) NOT NULL,
DEPT_LOCATION VARCHAR(50) NOT NULL,
EMP_ID INT FOREIGN KEY REFERENCES EMPLOYEES (EMP_ID) NOT NULL
)

SELECT DEPT_ID, DEPT_NAME,DEPT_LOCATION FROM DEPARTMENTS

SELECT * FROM EMPLOYEES

INSERT INTO EMPLOYEES VALUES (101, 'Charlie', '2024-01-01', 45000, 'Pune')
INSERT INTO EMPLOYEES VALUES (102, NULL, '2024-02-19', 34500, 'Delhi')